#!/usr/bin/env bash
# Install and configure HAproxy on your lb-01 server.

sudo apt update && sudo apt upgrade
sudo apt-get install --no-install-recommends software-properties-common
sudo add-apt-repository ppa:vbernat/haproxy-2.8
sudo apt-get install haproxy=2.8.\* -y

load_balancer="\nfrontend http\n
\tbind *:80
\tmode http
\tdefault_backend load_b

backend load_b\n
\tbalance roundrobin
\tserver web-01 35.153.66.11 check
\tserver web-02 100.26.154.224 check
"
echo -e "ENABLED=1\n" | sudo tee -a /etc/default/haproxy
echo -e "$load_balancer" | sudo tee -a /etc/haproxy/haproxy.cfg
service haproxy restart
