#!/usr/bin/env bash
# A script that Displays numbers from 1 to 100 in list format.
# Displays "FizzBuzz" when the number is a multiple of 3 and 5.
# Displays "Fizz" when the number is a multiple of 3.
# Displays "Buzz" when the number is a multiple of 5.
# Otherwise, displays the number.

for myvar in {1..100}
do
  if (( myvar % 3 == 0 && myvar % 5 == 0 ))
  then
    echo "FizzBuzz"
  elif (( myvar % 3 == 0 ))
  then
    echo "Fizz"
  elif (( myvar % 5 == 0 ))
  then
    echo "Buzz"
  else
    echo "$myvar"
  fi
   myvar=$(( myvar + 1 ))
 done
