#!/usr/bin/env bash
#a Bash script that displays numbers from 1 to 100.
#Displays FizzBuzz when the number is a multiple of 3 and 5
#Displays Fizz when the number is multiple of 3
#Displays Buzz when the number is a multiple of 5
#Otherwise, displays the number

myvar=0

for myvar in {1..100}
do
	if [ $((myvar % 3)) -eq 0 ] && [ $((myvar % 5)) -eq 0 ]
	then
		echo "FizzBuzz"
	elif [ $((myvar % 3)) -eq 0 ]
	then
		echo "Fizz"
	elif [ $((myvar % 5)) -eq 0 ]
	then
		echo "Buzz"
	else
		echo "$myvar"
fi
done
