#!/usr/bin/env bash
#Displays 'Best School' 10 times but the 9th dispays 'Best School Hi'

myvar=1

while [ $myvar -le 10 ]
do
	if [ $myvar -eq 9 ]
	then
		echo "Best School"
		echo "Hi"
	else
		echo "Best School"
	fi
	myvar=$(( myvar + 1 ))
done
