#!/usr/bin/env bash
# A script that Displays "Best School" 10 times using a while loop.
# On the 9th iteration, displays "Hi" before "Best School".

myvar=0

while [ $myvar -lt 10 ]
do
  if [ $myvar -eq 9 ]
  then
    echo "Hi"
  fi
  echo "Best School"
  (( myvar++ ))
done
