#!/usr/bin/env bash
# A script that Loops from 1 to 10 and displays:
#   "bad luck" for the 4th iteration
#   "good luck" for the 8th iteration
#   "Best School" for all other iterations

myvar=0

while [ $myvar -lt 10 ]
do
  if [ $myvar -eq 3 ]
  then
    echo "bad luck"
  elif [ $myvar -eq 7 ]
  then
    echo "good luck"
  else
    echo "Best School"
  fi
  (( myvar++ ))
done
