#!/usr/bin/env bash
#Displays "Best School" 10 times but the 4th id displays 'bad luck" and the 8th displays "good luck"

myvar=1

while [ $myvar -le 10 ]
do
	if [ $myvar -eq 4 ]
	then
		echo "bad luck"
	elif [ $myvar -eq 8 ]
	then
		echo "good luck"
	else
		echo "Best School"
	fi
	myvar=$(( myvar + 1 ))
done	
