#!/usr/bin/env bash
#Displays  numbers from 1 to 20 and: displays 4 and then bad luck from china
#Then on the 9th it displays bad luck from Japan
#Then on the 17th bad luck from italy

myvar=1

while [ $myvar -le 20 ]
do
	echo "$myvar"
	case $myvar in
	4)
		echo "bad luck from China";;
	9)
		echo "bad luck from Japan";;
	17)
		echo "bad luck from Italy";;
	esac
		(( myvar++ ))
done
