#!/usr/bin/env bash
#Displays the time for 12 hours and 59 minutes, It displays hours from 0 to 12 ,It also displays minutes from 1 to 59

H=0
while [ $H -le 12 ]
do
	echo "Hour: $H"
	M=1
	while [ $M -le 59 ]
	do
		echo $M
		((M++))
	done
	((H++))
done
