#!/usr/bin/env bash
# A script that Displays the contents of the current directory in list format.
#   Only displays the part of the name after the first dash. 

myvar=$(ls)
for i in $myvar; do
  echo "$i" | cut -d '-' -f2
done

